#!/bin/bash

## #ddev-generated
## Description: Display Varnish request histogram
## Usage: varnishhist
## Example: "ddev varnishhist"

# This example runs inside the varnish container.
# Note that this requires that /mnt/ddev_config be mounted
# into the varnish container.

varnishhist "$@"
