#!/bin/bash

WRITABLE=$(grep "#ddev-generated" .ddev/varnish/default.vcl)
if [ "$WRITABLE" == "" ]; then
    echo "❗️ '#ddev-generated' not found in ddev/varnish/default.vcl -  file is protected "
    exit    
fi

PATH_VCL=vendor/ibexa/http-cache/docs/varnish/vcl/varnish6.vcl
if [ -f $PATH_VCL ]; then
    ddev exec cp "$PATH_VCL" .ddev/varnish/default.vcl
    ddev exec sed -i '1s/^/\/\/#ddev-generated\n/' .ddev/varnish/default.vcl
    ddev exec sed -i 's#/etc/varnish/parameters.vcl#parameters.vcl#g'  .ddev/varnish/default.vcl
    ddev exec sed -i 's#parameters.vcl#./parameters.vcl#g'  .ddev/varnish/default.vcl
    
    echo "✅ Copied vcl from vendor/ibexa/http-cache/docs/"
fi
