#!/bin/bash

VARNISH_VERSION=""
DXP_VERSION=""

if [ $# -eq 2 ]; then
    VARNISH_VERSION="$1"
    DXP_VERSION="$2"
else
    if [[ "$VARNISH_IMAGE_VERSION" = "6."*  ]]; then
        VARNISH_VERSION=6
    elif [[ "$VARNISH_IMAGE_VERSION" = "7."*  ]]; then
        VARNISH_VERSION=7
    fi
    
    if [[ "$DXP_RELEASE" =~ ^(~|v)?4\.6\. ]]; then
        DXP_VERSION="4"
    elif [[ "$DXP_RELEASE" =~ ^(~|v)?5\.0\. ]]; then
        DXP_VERSION="5"
    fi
fi


if [[ $VARNISH_VERSION != "7" && $VARNISH_VERSION  !=  "6"  ]]; then
  echo "❗️ No valid varnish version "
  exit
fi

if [[ $DXP_VERSION != "4" && $DXP_VERSION  !=  "5"  ]]; then
  echo "❗️ No valid dxp version "
  exit
fi


PATH_VCL="vendor/ibexa/http-cache/docs/varnish/vcl/varnish$VARNISH_VERSION.vcl"
if [ ! -f $PATH_VCL ]; then
    PATH_VCL="varnish/v$DXP_VERSION/varnish$VARNISH_VERSION.vcl"
fi

if [ ! -f $PATH_VCL ]; then
  echo "❗️ No vcl file found - default vcls are used"
  exit
fi

# default.vcl writable ?  
WRITABLE=$(grep "#ddev-generated" .ddev/varnish/default.vcl)

if [ "$WRITABLE" == "" ]; then
    echo "❗️ '#ddev-generated' not found in ddev/varnish/default.vcl -  file is protected "
else
    # replace default.vcl
    cp "$PATH_VCL" .ddev/varnish/default.vcl
    
    sed -i '1s/^/\/\/#ddev-generated\n/' .ddev/varnish/default.vcl
    sed -i 's#/etc/varnish/parameters.vcl#parameters.vcl#g'  .ddev/varnish/default.vcl
    sed -i 's#parameters.vcl#./parameters.vcl#g'  .ddev/varnish/default.vcl
    
    echo "✅ Copied vcl from $PATH_VCL"
fi

# parameters.vcl writable ?  
WRITABLE=$(grep "#ddev-generated" .ddev/varnish/parameters.vcl)
if [ "$WRITABLE" == "" ]; then
    echo "❗️ '#ddev-generated' not found in ddev/varnish/parameters.vcl -  file is protected "
    exit    
fi

# ibexa or ezplatform ?
IBEXA_BACKEND=$(grep "req.backend_hint = ibexa" "$PATH_VCL")
if [[ "$IBEXA_BACKEND" != "" ]]; then
    sed -i 's#backend ezplatform#backend ibexa#g'  .ddev/varnish/parameters.vcl
    echo "✅ Set *backend ibexa* in parameters.vcl"
fi
